<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!--
            Revit |  .NET Framework: 
            2014  |  net40
            2015  |  net45
            2016  |  net451
            2017  |  net452
            2018  |  net46
            2019  |  net47
            2020  |  net471
            2021  |  net48
            2022  |  net48
            2023  |  net48
            2024  |  net48
            2025  |  net8.0
            2026  |  net8.0
            2027  |  net10.0
        -->

        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>

        <TargetFramework>net8.0</TargetFramework> <!-- Default .NET Framework -->
        <!--<DefineConstants>REVIT2022;WINFORMS</DefineConstants> --> <!-- Change based on default .net framework -->
        <RevitVersion>2025</RevitVersion>
        
        <Configurations>Debug R22;Debug R23;Debug R24;Debug R25;Debug R26;Debug R27;Release R22;Release R23;Release R24;Release R25;Release R26;Release R27</Configurations>
        <UseWPF>true</UseWPF>
        <Platforms>AnyCPU</Platforms>

    </PropertyGroup>
    
    <PropertyGroup Condition="$(Configuration.Contains('R22'))">
        <RevitVersion>2022</RevitVersion>
        <TargetFramework>net48-windows</TargetFramework>
        <DefineConstants>REVIT2022;WINFORMS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="$(Configuration.Contains('R23'))">
        <RevitVersion>2023</RevitVersion>
        <TargetFramework>net48-windows</TargetFramework>
        <DefineConstants>REVIT2023;WINFORMS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="$(Configuration.Contains('R24'))">
        <RevitVersion>2024</RevitVersion>
        <TargetFramework>net48-windows</TargetFramework>
        <DefineConstants>REVIT2024;WINFORMS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="$(Configuration.Contains('R25'))">
        <RevitVersion>2025</RevitVersion>
        <TargetFramework>net8.0-windows</TargetFramework>
        <DefineConstants>REVIT2025;WINFORMS</DefineConstants>
    </PropertyGroup>
    
    <PropertyGroup Condition="$(Configuration.Contains('R26'))">
        <RevitVersion>2026</RevitVersion>
        <TargetFramework>net8.0-windows</TargetFramework>
        <DefineConstants>REVIT2026;WINFORMS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="$(Configuration.Contains('R27'))">
        <RevitVersion>2027</RevitVersion>
        <TargetFramework>net10.0-windows</TargetFramework>
        <DefineConstants>REVIT2027;WINFORMS</DefineConstants>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="2027.*" Condition="'$(RevitVersion)' == '2027'" PrivateAssets="All" />
        <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="2026.*" Condition="'$(RevitVersion)' == '2026'" PrivateAssets="All" />
        <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="2025.*" Condition="'$(RevitVersion)' == '2025'" PrivateAssets="All" />
        <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="2024.*" Condition="'$(RevitVersion)' == '2024'" PrivateAssets="All" />
        <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="2023.*" Condition="'$(RevitVersion)' == '2023'" PrivateAssets="All" />
        <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="2022.*" Condition="'$(RevitVersion)' == '2022'" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resources\RenamerIcon.png" />
      <None Remove="Resources\ElectricalCircuit.png" />
      <None Remove="Resources\GPSrvtTabDLLMover.exe" />
      <None Remove="Resources\Receptacle32.png" />
      <EmbeddedResource Include="Resources\Receptacle32.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="Resources\Concat32.png" />
      <None Remove="Resources\ConcatIcon.png" />
      <None Remove="Resources\Download32.png" />
      <EmbeddedResource Include="Resources\Download32.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="Resources\SheetRev16.png" />
      <EmbeddedResource Include="Resources\SheetRev16.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="Resources\AwsRev16.png" />
      <EmbeddedResource Include="Resources\AwsRev16.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="Resources\PrintSet32.png" />
      <EmbeddedResource Include="Resources\PrintSet32.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="Resources\DeleteParameter16.png" />
      <EmbeddedResource Include="Resources\DeleteParameter16.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
      <None Remove="Resources\DeleteFamilySymbol16.png" />
      <EmbeddedResource Include="Resources\DeleteFamilySymbol16.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <!--<ProjectReference Include="..\GPSrvtTab.Contracts\GPSrvtTab.Contracts.csproj" />-->
        <ProjectReference Include="..\GPSrvtTabWrapper\GPSrvtTabWrapper.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Resources\Concat32.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
    </ItemGroup>
    

</Project>
